### ISSUE TITLE
New Property P5536

### ISSUE THREAD

**Issue by salgo60** [maxlath/hub#10]
I guess we need a restart
- * WD: [Q10688474](https://www.wikidata.org/wiki/Special:Search?search=haswbstatement%3AP5536%3D1xx001%2F504225b1&fulltext=Search+for+%271ex001%2F304209c1%27&fulltext=Search&searchToken=94ropzykiewjwxlhdqt7jw4kr) https://tools.wmflabs.org/hub/P5536:1xx001/504225b1?property=P625
- *  WD:[Q10532246](https://www.wikidata.org/wiki/Q10532246)  https://tools.wmflabs.org/hub/P5536:1ex001/304209c1?property=P625

**Comment by salgo60** [comment]
Same problem with P5587
* https://tools.wmflabs.org/hub/P906:187465?property=P20|P5587

**Comment by maxlath** [comment]
done. I'm closing this issue but you can add a comment here to request a new restart, I should get the notification. (Until the issue with daily properties refresh is fixed ;))

**Comment by salgo60** [comment]
Thanks let me know if your future plans change for this service as I try to push people at the Swedish National Archives to use it https://phabricator.wikimedia.org/T200181

**Comment by maxlath** [comment]
@salgo60 so far, the work required by service maintenance is acceptable so I will keep supporting it in the near future, and will of course let you and the community know if that change :)

**Comment by salgo60** [comment]
New property P6192 ==> we need a restart

https://minancestry.blogspot.com/2018/12/bygdeband-swedish-site-containing-local.html

**Comment by salgo60** [comment]
New property P7607 created and we need a restart Thanks

See [T239159](https://phabricator.wikimedia.org/T239159)

**Comment by maxlath** [comment]
@salgo60 I restarted the server, and it seems to work now
