### ISSUE TITLE
Certain kinds of URL calls do not work any more

### ISSUE THREAD

**Issue by VojtechDostal** [maxlath/hub#11]
Links such as this one:
https://tools.wmflabs.org/hub/P782:CZ558877?lang=cs

Also many examples from the Hub page don't work any more:
https://tools.wmflabs.org/hub/

**Comment by maxlath** [comment]
Thanks for reporting, this is due to the application of the [wikimedia user agent policy](https://meta.wikimedia.org/wiki/User-Agent_policy) on query.wikidata.org, that now returns 403 errors when the requests are made without user-agent. That shouldn't be too hard to fix

**Comment by maxlath** [comment]
fixed by e30e40b and online now! :)

**Comment by VojtechDostal** [comment]
Thank you Maxime :)

**Comment by maxlath** [comment]
@VojtechDostal you're welcome :D
