### ISSUE TITLE
Hywwiki-caused error?

### ISSUE THREAD

**Issue by VojtechDostal** [maxlath/hub#12]
Hello, it seems the tools is unable to follow to a Wikidata item if this Wikidata item has a hyw wiki sitelink. [These](https://w.wiki/7Ex) are all items which have our identifier P5398 and also have a hywwiki sitelink. They all do not work on Wikidata Hub, eg:

https://tools.wmflabs.org/hub/P5398:000016820?site=wikidata

https://tools.wmflabs.org/hub/P5398:000002772?site=wikidata

Could you please look at it?

**Comment by maxlath** [comment]
thanks for reporting! fixed by 08734b0 and e40958e, now online

**Comment by VojtechDostal** [comment]
Thank you! :blush:
