### ISSUE TITLE
allow access to props by name

### ISSUE THREAD

**Issue by VladimirAlexiev** [maxlath/hub#14]
- These return "invalid property id: undefined": https://tools.wmflabs.org/hub/PermID:4295899948, https://tools.wmflabs.org/hub/permid:4295899948 (note: that's P3347: PermID)
- This goes to the right WP page: https://tools.wmflabs.org/hub/viaf:124291214. So obviously Hub knows the mapping of "viaf" to a prop number
- It would be excellent if you use WD prop labels to do such mappings automatically
- this applies to the source prop, but also the target `property=`. Eg the following
https://tools.wmflabs.org/hub/viaf:24597135?property=P1938 could be written more nicely as https://tools.wmflabs.org/hub/viaf:24597135?property=gutenberg

**Comment by maxlath** [comment]
following ca83876, all those cases should now be working \o/
