### ISSUE TITLE
Get image attribution searching with property 'image'

### ISSUE THREAD

**Issue by orionseye** [maxlath/hub#15]
I am curious, since '?property=image' resolves to an image, is there a way to get the image attribution?
Saw that you implemented JSON output as well...will it make sense to query in json format and get image and attribution in return?
Thx for this superb tool :)

**Comment by maxlath** [comment]
you're welcome, curious to know your use case :)

you could get the filename from the JSON output
https://tools.wmflabs.org/hub/frwiki:Laniakea?property=image&width=256&format=json

and then request the image attribution with it using https://tools.wmflabs.org/magnus-toolserver/commonsapi.php ([example](https://tools.wmflabs.org/magnus-toolserver/commonsapi.php?image=File:Observable_universe_r2.jpg)

**Comment by orionseye** [comment]
Hello maxlath, thank you for the input.
Of course, i am building a destination map using OSM data and make use of its available tags , among others, the 'image' , 'wikimedia' and wikidata tag to retrieve POI related media.
`if (img.indexOf('File') === 0) {`  .. and similar function for wikidata 'Q.....'
I was impressed how much data wikidata returns, so i stumbled across /hub/ and it's '?property=image'
Now. more than 60% of all my pois have media, where with OSM only, it was just 5-10%
Since i want to play fair, i already attribute wikimedia authors..but had problem to attribute wikidata images.
Which now seems to be past :) Great solution! 
And a dump question at the end:
For production use, should i use /hub/ online or install it on my server?

**Comment by maxlath** [comment]
I think you can use https://tools.wmflabs.org/hub/ in production, but keep in mind that depending your starting point, there might be more performant ways to get what you want. some ideas:
- if you already have a Wikimedia Commons filename at hand, directly using the https://commons.wikimedia.org/wiki/Special:FilePath endpoint can spare you a redirection
- using wikidata Q ids as a starting point is generally less work than using other ids (sparing that id resolution that sometimes requires a SPARQL request)
- for maximum performance, and depending on your setup, you might want to cache the final URL, using the hub as just an API to resolve your ids

**Comment by orionseye** [comment]
Yes, that's exactly what i'm doing regarding 1st recommendation, after splitting the url to get down to the image file name
`img = 'https://commons.wikimedia.org/wiki/Special:FilePath/' + encodeURIComponent(url[2]);`

Regrading 3rd, i don't follow exactly what you mean 'caching final URL'
Do you mean, caching 'https://tools.wmflabs.org/hub/ ' and the querying each Q... with JSON
e.g. '?property=image&width=256&format=json' ?

Thank you again for the ideas

**Comment by orionseye** [comment]
Hi @maxlath 
i have another question. Trying to get banner images of wikivoyage articles, it works fine with cases where:
New York City (New_York_City)
London
Sydney
...etc
using https://tools.wmflabs.org/hub/enwiki:London?property=P948&width=450

How do i deal with Destination names, either in sub-directories or enclosed in parenthesis?
e.g. 
https://en.wikivoyage.org/wiki/Tokyo/Shinjuku
image can be retrieved using:
https://tools.wmflabs.org/hub/enwiki:Shinjuku?property=P948&width=450

Not sure if this is the correct way .. but it works

Another case would be:
https://en.wikivoyage.org/wiki/London_(Ontario)
https://en.wikivoyage.org/wiki/London_(Arkansas)

Lookup for Ontario or Arkansas makes no sense.
Could you help please?
:)

**Comment by maxlath** [comment]
those should work:
* https://tools.wmflabs.org/hub/enwikivoyage:London_(Ontario)?property=P948&width=450
* https://tools.wmflabs.org/hub/enwikivoyage:Tokyo/Shinjuku?format=json&property=P948&width=450

notice that I use `enwikivoyage` and not `enwiki` which is for the English Wikipedia

**Comment by orionseye** [comment]
You saved my work .. again. So great, totally missed the wv part. Thank you!
