### ISSUE TITLE
MIME type issue for non existing images with wikidata query

### ISSUE THREAD

**Issue by orionseye** [maxlath/hub#19]
Hi maxlath :)

I am querying hub with lots of destination data, with php
https://tools.wmflabs.org/hub/' . $poi['wikidata'] . '?property=image&width=250

Some of the images are missing and (of course)
a) not available with the results
b) the download is blocked by the browser because  of MIME type text/html
(a non existing image redirects to the wikidata page)

Here some examples
https://tools.wmflabs.org/hub/Q321674?property=image&width=250
https://tools.wmflabs.org/hub/Q32689091?property=image&width=250
https://tools.wmflabs.org/hub/Q269622?property=image&width=250

Is there a way to avoid such behavior or do i have todo the mime type check server side with mime_content_type?
..which is a headache

Thanks a lot!

**Comment by maxlath** [comment]
hi!

would that work for you if it returned a 404 in such case?

**Comment by orionseye** [comment]
Yes, better than nothing.
I mean, i temp. fixed it with javascript, and such entries get either a fallback image or get deleted.
But a 404 would be fine.
Thank you :)

**Comment by maxlath** [comment]
I added a [fallback mechanism](https://github.com/maxlath/hub#fallback):
```sh
# respond with a 404
https://hub.toolforge.org/Q321674?property=image&width=250&fallback=404
# redirects to https://upload.wikimedia.org/wikipedia/commons/e/e0/Wikimedia_error_404.png
https://hub.toolforge.org/Q32689091?property=image&width=250&fallback=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fe%2Fe0%2FWikimedia_error_404.png
```

**Comment by orionseye** [comment]
Perfect, Makes the work easier.
Have a great weekend!
