### ISSUE TITLE
Bug with wikidata route?

### ISSUE THREAD

**Issue by dpriskorn** [maxlath/hub#22]
![bild](https://user-images.githubusercontent.com/68460690/152560336-f6176897-8f53-4f3e-a200-ec8b3e138205.png)
The code is here:
https://github.com/dpriskorn/asseeibot/blob/4784c1db47c99e3cb6d0db820b7fe3e89da5b2ef/asseeibot/models/wikimedia/wikidata/scientific_item.py#L36

I expected either a 200 response with a QID or a 400 response. As you see in the screenshot I got a wikipedia link instead.

DOI: 10.1103/revmodphys.29.547

**Comment by maxlath** [comment]
there is a problem in the querystring in the URL you build:
```
url = f"https://hub.toolforge.org/doi:{quote(doi)}?site:wikidata?format=json"
```
it should rather be
```
url = f"https://hub.toolforge.org/doi:{quote(doi)}?site=wikidata&format=json"
```
otherwise the site parameter won't be taken into account
