### ISSUE TITLE
Incorrect URL for lexemes

### ISSUE THREAD

**Issue by jhsoby** [maxlath/hub#24]
Hi! I just tried this with a lexeme property: https://hub.toolforge.org/P10041:19380 and it redirects to the wrong URL. The "Lexeme:" namespace is missing. Could you please fix that?

**Comment by maxlath** [comment]
Indeed! Should now have been fixed by 8e07ee6

**Comment by jhsoby** [comment]
That was quick! Thank you, and merry Christmas!

**Comment by maxlath** [comment]
Merry Winter Solstice Jon! :tada:
