### ISSUE TITLE
Use as JSON API 

### ISSUE THREAD

**Issue by nichtich** [maxlath/hub#5]
`site=json` could emit the result in JSON. `site=json,xxx` could be used to debug/inspect result of query form `site=xxx`, e.g

    /aat:300310603?site=json&lang=fr

~~~json
{
  "context": {
    "text": "aat:300310603",
    "lang": "fr"
  },
  "properties": [ "P1014", "P3710" ],
  "value": "300310603",
  "site": "wiki",
  "entityUrl": "https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q47093172&format=json&props=sitelinks",
  "sitelink": null,
  "fallbackSitelink": { "site": "wikidata", "title": "Q47093172", "score": 0 },
  "url": "https://www.wikidata.org/wiki/Q47093172"
}
~~~

Or at least the `url` value. Format might be different, e.g. move fields into `context` (also available on error documents so it should have same format).

**Comment by maxlath** [comment]
I tried something with `format=json` instead, as site would conflict with the parsing of normal requests, while passing a format allows to collect the context progressively and simply alter the final response
commit: 46c0ba4
doc: https://github.com/maxlath/hub#json

what do you think?
ex: https://tools.wmflabs.org/hub/Q2?format=json

**Comment by nichtich** [comment]
Thanks for implementation!

**Comment by maxlath** [comment]
you're welcome!
